Repository nadianogues/blog-angular-node, pull requests merged in 2019-11, with the labels that each got.

#34 9 function to get last n posts
  package-lock.json
  package.json
  src/server/server.js
Labels: back-end

#35 #33 Fix hero component
  src/app/about/about.component.html
  src/app/about/about.component.scss
  src/app/app.component.html
  src/app/app.module.ts
  src/app/background-menu/background-menu.component.html
  src/app/background-menu/background-menu.component.scss
  src/app/background-menu/background-menu.component.ts
  src/app/hero/hero.component.scss
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/menu/menu.component.scss
  src/assets/images/background.jpg
Labels: bug, front-end, help wanted

#37 36 update home page
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/posts.service.ts
  src/app/shared/post.model.ts
  src/server/server.js
Labels: back-end, front-end

#39 38 update post page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/post-page/post-page.component.html
  src/app/post-page/post-page.component.ts
  src/app/post/post.component.ts
  src/app/posts.service.ts
  src/app/shared/comment.model.ts
  src/app/shared/post.model.ts
  src/server/server.js
Labels: back-end

#40 15 contact page
  bd/blog.sql
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/contact/contact.component.html
  src/app/contact/contact.component.scss
  src/app/contact/contact.component.ts
  src/app/menu/menu.component.html
  src/app/menu/menu.component.scss
  src/app/menu/menu.component.ts
  src/assets/images/github.png
  src/assets/images/linkedin.png
  src/styles.scss
Labels: back-end, front-end, low-priority

#42 #15 Add back-end contact page
  src/app/add-comment/add-comment.component.html
  src/app/app.module.ts
  src/app/contact.service.ts
  src/app/contact/contact.component.html
  src/app/contact/contact.component.ts
  src/app/login/login.component.html
  src/app/menu/menu.component.ts
  src/app/shared/contact.model.ts
  src/server/server.js
  src/styles.scss
Labels: back-end, front-end, low-priority

#44 41 login implementation
  bd/blog.sql
  src/app/about/about.component.ts
  src/app/app.module.ts
  src/app/contact/contact.component.ts
  src/app/home/home.component.ts
  src/app/login.service.ts
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/menu/menu.component.html
  src/app/menu/menu.component.scss
  src/app/menu/menu.component.ts
  src/app/post-page/post-page.component.ts
  src/app/posts.service.ts
  src/app/shared/user.model.ts
  src/server/server.js
Labels: back-end, front-end

#46 43 new post page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/contact/contact.component.html
  src/app/contact/contact.component.scss
  src/app/contact/contact.component.ts
  src/app/menu/menu.component.html
  src/app/new-post/new-post.component.html
  src/app/new-post/new-post.component.scss
  src/app/new-post/new-post.component.ts
  src/app/posts.service.ts
  src/server/server.js
Labels: back-end, front-end

#49 #48 Fix post-item
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/post-item/post-item.component.scss
  src/app/util/reduced.description.pipe.ts
Labels: front-end

#50 #11 Function to add comment post
  src/app/comment.service.ts
  src/app/home/home.component.ts
  src/app/login/login.component.ts
  src/server/server.js
Labels: back-end

#51 #47 Add new user page
  src/app/app.module.ts
  src/app/contact/contact.component.ts
  src/app/login.service.ts
  src/app/login/login.component.ts
  src/app/menu/menu.component.html
  src/app/menu/menu.component.scss
  src/app/menu/menu.component.ts
  src/app/new-post/new-post.component.html
  src/app/new-post/new-post.component.ts
  src/app/new-user/new-user.component.html
  src/app/new-user/new-user.component.scss
  src/app/new-user/new-user.component.ts
  src/app/posts.service.ts
  src/app/shared/user.model.ts
  src/assets/images/new-user.png
  src/server/server.js
Labels: back-end, front-end

#52 #45 Add comment working
  src/app/add-comment/add-comment.component.html
  src/app/add-comment/add-comment.component.ts
  src/app/home/home.component.ts
  src/app/post-page/post-page.component.html
  src/app/post-page/post-page.component.scss
  src/assets/images/avatar.png
  src/server/server.js
Labels: back-end, front-end

#54 #53 Add pagination to home page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/pagination/pagination.component.html
  src/app/pagination/pagination.component.scss
  src/app/pagination/pagination.component.ts
  src/app/posts.service.ts
  src/server/server.js
Labels: back-end, front-end

#57 18 text editor new post
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/menu/menu.component.html
  src/app/new-post/new-post.component.html
  src/app/pagination/pagination.component.html
  src/app/pagination/pagination.component.scss
  src/app/pagination/pagination.component.ts
  src/app/post-item/post-item.component.html
  src/app/post-page/post-page.component.html
  src/app/post/post.component.html
  src/app/post/post.component.ts
  src/app/util/reduced.description.pipe.ts
  src/assets/images/hero2.jpg
Labels: back-end

#59 #58 Fix problems
  src/app/add-comment/add-comment.component.html
  src/app/add-comment/add-comment.component.ts
  src/app/app-routing.module.ts
  src/app/comment/comment.component.html
  src/app/contact/contact.component.scss
  src/app/menu/menu.component.html
  src/app/post-page/post-page.component.html
  src/app/post-page/post-page.component.scss
  src/app/util/reduced.description.pipe.ts
Labels: bug
