Repository nadianogues/blog-angular-node, pull requests merged in 2019-10, with the labels that each got.

#2 add database
  bd/blog.sql
Labels: database

#19 Update README.md
  README.md
Labels: documentation

#20 Post component
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/post/post.component.html
  src/app/post/post.component.scss
  src/app/post/post.component.ts
  src/index.html
  src/styles.scss
Labels: enhancement, front-end

#21 Update README.md
  README.md
Labels: documentation

#25 Add login screen
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.ts
  src/styles.scss
Labels: front-end

#26 17 post page
  src/app/add-comment/add-comment.component.scss
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/comment/comment.component.html
  src/app/comment/comment.component.scss
  src/app/post-item/post-item.component.html
  src/app/post-item/post-item.component.scss
  src/app/post-item/post-item.component.ts
  src/app/post-page/post-page.component.html
  src/app/post-page/post-page.component.scss
  src/app/post-page/post-page.component.ts
  src/app/post/post.component.html
  src/app/post/post.component.scss
  src/app/post/post.component.ts
  src/styles.scss
Labels: front-end

#27 #6 Finished main menu component
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/menu/menu.component.html
  src/app/menu/menu.component.scss
  src/app/menu/menu.component.ts
  src/assets/images/logo.png
  src/styles.scss
Labels: front-end

#29 16 layout main page
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/post-item/post-item.component.scss
  src/app/post-item/post-item.component.ts
Labels: front-end

#30 28 hero component
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/hero/hero.component.html
  src/app/hero/hero.component.scss
  src/app/hero/hero.component.ts
  src/app/menu/menu.component.scss
  src/assets/images/black_logo.png
  src/assets/images/hero.jpg
  src/styles.scss
Labels: front-end

#31 #7 Update database structure
  bd/blog.sql
Labels: database

#32 #14 Add about screen
  src/app/about/about.component.html
  src/app/about/about.component.scss
  src/app/about/about.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/menu/menu.component.html
  src/assets/images/nadia.jpg
  src/assets/images/rodrigo.jpg
Labels: front-end, low-priority
